# Generated by Django 3.1.6 on 2021-02-20 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210220_1604'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='matchingreview',
            table='matching_reivews',
        ),
        migrations.AlterModelTable(
            name='productinquiry',
            table='product_inquiries',
        ),
    ]
