# Generated by Django 3.1.6 on 2021-02-20 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210220_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchingreview',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.review'),
        ),
    ]
