# Generated by Django 3.1.6 on 2021-02-22 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210220_1739'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='matchingreview',
            table='matching_reviews',
        ),
    ]
