# Generated by Django 3.1.6 on 2021-02-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_address',
            new_name='home_address',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_password',
            new_name='password',
        ),
        migrations.AlterField(
            model_name='user',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
    ]
