# Generated by Django 3.1.6 on 2021-02-23 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210223_1157'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cartstatus',
            table='cart_statuses',
        ),
    ]
